# CCSG model configuration with alignment loss
# This extends the base CCSG configuration with optional alignment loss

_target_: xtalnet.pl_modules.ccsg_module.CSPDiffusion
time_dim: 256
latent_dim: 512
cost_coord: 1.
cost_lattice: 1.
timesteps: 1000
pretrained: ${data.pretrained}
freeze_pxrd_encoder: true

# ALIGNMENT: Optional alignment loss configuration
# Set use_alignment_loss=true to enable alignment with CPCP embeddings
use_alignment_loss: false  # Set to true to enable
cpcp_ckpt_path: null  # Path to CPCP checkpoint (required if use_alignment_loss=true)
alignment_lambda: 0.1  # Weight for alignment loss (0.05-0.2 recommended)
alignment_temperature: 0.1  # Temperature for InfoNCE loss (0.07-0.15 recommended)
alignment_start_epoch: 0  # Epoch to start applying alignment loss (0 for immediate)

defaults:
  - crystal_encoder: ccsg_crystal
  - beta_scheduler: cosine
  - sigma_scheduler: wrapped
  - pxrd_encoder: bert
